version: "3"
services:
  server:
    user: ${UID}:${GID}
    container_name: server
    build:
      context: ../
      dockerfile: ./docker/server.dockerfile
    volumes:
      - ../:/var/www
    working_dir: /var/www
