version: "3"
services:
  server:
    user: ${UID}:${GID}
    container_name: server
    build:
      context: ../
      dockerfile: ./docker/server.dockerfile
    volumes:
      - ../:/var/www
    working_dir: /var/www
    networks:
      - demo-network
    ports:
      - "8080:8080"
    command: php artisan serve --host 0.0.0.0 --port 8080

networks:
  demo-network:
